/* eslint-disable @typescript-eslint/no-unused-vars */
import {
  Account,
  BillerInfo,
  Customer,
  ID,
  MyBank,
  MyEarning,
  MyWallet,
  Notty,
  PrinterObj,
  Referral,
  Transaction,
  User,
  Variation,
  Withdrawal,
} from './types';

/* let js = {
  accept_field_label: '',
  allow_variation_amount_edit: 0,
  convinience_fee: 0,
  description: 'Airtel airtime - Get instant top up',
  description2: '',
  image:
    'https://localhost:8888/vtpassstager4/resources/products/200X200/Airtel-Airtime.jpg',
  is_mobile_voucher: false,
  is_quantity: false,
  is_unique: false,
  maximum_amount: '8000',
  minimium_amount: '50',
  name: 'Airtel Airtime VTU',
  page_type: 'regular',
  product_id: 1,
  product_type: 'flexible',
  quantity_label: '',
  serviceID: 'airtel',
  unique_element: false,
  unique_element_description: false,
  var_count: false,
  variations: '',
};

let data = {
  accept_field_label: '',
  allow_variation_amount_edit: 0,
  convinience_fee: 0,
  description: 'Airtel Data - Get instant top up',
  description2: '',
  image:
    'https://localhost:8888/vtpassstager4/resources/products/200X200/Airtel-Data.jpg',
  is_mobile_voucher: false,
  is_quantity: false,
  is_unique: false,
  maximum_amount: '1000000',
  minimium_amount: '1',
  name: 'Airtel Data',
  page_type: 'regular',
  product_id: 7,
  product_type: 'fix',
  quantity_label: '',
  serviceID: 'airtel-data',
  unique_element: false,
  unique_element_description: false,
  var_count: true,
  variations: {
    countries: [Array],
    foreign_variation: [Array],
    variation_name: 'type',
    variations: [Array],
  },
};
let u = {
  country: 'Cameroon',
  details: {
    id: 'CM',
    flag: 'http://10.0.2.16:8080/resources/images/flags/CM.png',
    text: 'Cameroon',
    currency: 'XAF',
    country_prefix: '237',
  },
};
 */

export const variationSchema: Variation = {
  variation: '',
  amount: 0,
  identifier: '',
  product_id: 0,
  is_unique: false,
  unique_element: false,
  unique_element_description: false,
  is_quantity: false,
  is_mobile_voucher: false,
};

export const transactionSchema: Transaction = {
  id: 0,
  transactionId: 0,
  amount: 0,
  convinience_fee: 0,
  reference: '0',
  method: '',
  wepaid_gateway_fee: '',
  customer_id: 0,
  name: '',
  phone: '',
  email: '',
  type: '',
  created_at: '',
  updated_at: '',
  reason: '',
  payment_response: '',
  payment_description: '',
  discount: '',
  giftcard_id: '',
  total_amount: 0,
  is_api: 0,
  commission: '',
  channel: '',
  referral_id: '',
  extras: '',
  service_verification: '',
  memo: '',
  is_flagged: 0,
  receipt_extras: '',
  quantity: 0,
  unit_price: 0,
  initiated_id: '',
  final_id: '',
  unique_element: '',
  product_id: 0,
  product_name: '',
  flagged_admin: '',
  vtpass_deposit_reference: '',
  customer_deposit_reference: '',
  platform: '',
  customer_processing_fee: '',
  deviceID: '',
  admin_id: 0,
  in_suspend: '',
  ip: '',
  cron_trial_no: 0,
  cron_last_trial: '',
  service_commission: 0,
  domain_id: 11,
  domain_convenience: '0.00',
  domain_commission: '0.00',
  external_requestId: '',
  src: '',
  idc: '',
  app_version: '',
  prodImg: '',
  status: '',
  receipt: '',
  extra_s: '',
};

export const transactionData = {
  loading: true,
  data: [transactionSchema],
  filter: [transactionSchema],
  key: '',
};

export const customer: Customer = {
  account_manager_id: 0,
  admin_id: 0 || '',
  affiliateId: 0,
  callback_url: '',
  category: '',
  commission: 0,
  created_at: '',
  customer_type: 0,
  domain_id: 0,
  email_verification_code: 0,
  gift_voucher_count: 0,
  id: 0,
  is_old: 0,
  is_verified: 0,
  lock_reason: '',
  reason: '',
  referral_id: 0,
  required_pass_change: 0,
  reset_time: 0,
  security_question_trial: 0,
  seen: 0,
  sms_count: 0,
  special_agent: 0,
  status: 'active' || 'inactive',
  sub_terminal_role: 0,
  sub_tp_role: 0,
  updated_at: '',
  user_id: 0,
  verification_code: 0,
  verify_count: 0,
  wallet: 0,
  wallet_min: '',
};

export const user: User = {
  api_authentication_type: '',
  api_key: '',
  bank_reference: '',
  bvn: 0,
  bvn_phone_number: '',
  campaign_flag: '',
  check_request_id: '',
  company_name: '',
  created_at: '',
  customer: customer,
  date_of_birth: '',
  domain_id: 0,
  duplicate_check: '',
  email: '',
  facebook: '',
  gender: '',
  home_address: '',
  id: 0,
  idc: '',
  image: '',
  ip_lock: 0,
  lastname: '',
  local_govt: '',
  middle_name: '',
  mobile_type: '',
  name: '',
  parent: '',
  phone: '',
  public_key: '',
  s_token: '',
  secret_key: '',
  src: '',
  state: '',
  status: 'active' || 'inactive',
  twitter: '',
  two_fa_pin: '',
  two_fa_status: 'in-active' || 'active',
  twofa_reset_token_expires: '',
  updated_at: '',
  w_token: '',
  wallet_lock: 0,
};

export const userID: ID = {
  id: 0,
  deviceToken: '',
  deviceId: '',
  userToken: '',
  login: false,
};

export const account: Account = { id: 0, name: '' };

export const myEarnings: MyEarning = {
  accounts: [account],
  earning_balance: 0,
  invites_count: 0,
  refer_status: 0,
  refer_system_status: 0,
  ta_status: 0,
  total_earned: 0,
  total_withdrawn: 0,
  tp_status: 0,
};

export const mywallet: MyWallet = {
  id: 0,
  account_reference: '',
  account_number: 0,
  account_name: '',
  bank_name: '',
  provider: '',
  trans_lower_amt: 0,
  trans_upper_amt: 0,
  daily_upper_limit: 0,
  charge_flat: 0,
  charge_percentage: 0,
  charge_cap: 0,
  bvn: 0,
  verification_status: '',
  date_created: '',
  customer_id: 0,
  email: '',
  creation_method: '',
  purpose: '',
  status: '',
  admin_id: 0,
  created_at: '',
  updated_at: '',
  domain_id: 0,
};

export const mybank: MyBank = {
  account_name: '',
  account_number: 0,
  alias: '',
  bank_name: '',
  created_at: '',
  customer_id: 0,
  domain_id: 0,
  id: 0,
  identifier: '',
  status: 'inactive',
  updated_at: '',
};

export const refSchema: Referral = {
  invites: [],
  invites_count: 0,
  refCode: 0,
  refLink: '',
  refMessage: '',
  refer_code_status: 0,
  refer_status: 0,
};

export const billerInfo: BillerInfo = {
  loading: false,
  code: '',
  content: {
    Customer_Name: '',
    Status: '',
    Due_Date: '',
    Customer_Number: '',
    Customer_Type: '',
    Current_Bouquet: '',
    Current_Bouquet_Code: '',
    Renewal_Amount: '',
    error: '',
  },
};

export const nottySchema: Notty = {
  id: 0,
  subject: '',
  date: '',
  flag: '',
  content: '',
  preamble: '',
};

export const pSchema: PrinterObj = {
  device_name: '',
  inner_mac_address: '',
};

export const withdrawal: Withdrawal = {
  account_name: '',
  account_number: '',
  admin_id: 0,
  amount: 0,
  bank_code: '',
  bank_details: '',
  bank_name: '',
  created_at: '',
  customer_id: 0,
  destination: '',
  duplicate_check: '',
  id: 0,
  method: '',
  raw_response: '',
  ref: '',
  remarks: '',
  requestId: 0,
  service_charge: '',
  status: '',
  total_amount: 0,
  type: '',
  updated_at: '',
};
