let js = {
  accept_field_label: '',
  allow_variation_amount_edit: 0,
  convinience_fee: 0,
  description: 'Airtel airtime - Get instant top up',
  description2: '',
  image:
    'https://localhost:8888/vtpassstager4/resources/products/200X200/Airtel-Airtime.jpg',
  is_mobile_voucher: false,
  is_quantity: false,
  is_unique: false,
  maximum_amount: '8000',
  minimium_amount: '50',
  name: 'Airtel Airtime VTU',
  page_type: 'regular',
  product_id: 1,
  product_type: 'flexible',
  quantity_label: '',
  serviceID: 'airtel',
  unique_element: false,
  unique_element_description: false,
  var_count: false,
  variations: '',
};

let data = {
  accept_field_label: '',
  allow_variation_amount_edit: 0,
  convinience_fee: 0,
  description: 'Airtel Data - Get instant top up',
  description2: '',
  image:
    'https://localhost:8888/vtpassstager4/resources/products/200X200/Airtel-Data.jpg',
  is_mobile_voucher: false,
  is_quantity: false,
  is_unique: false,
  maximum_amount: '1000000',
  minimium_amount: '1',
  name: 'Airtel Data',
  page_type: 'regular',
  product_id: 7,
  product_type: 'fix',
  quantity_label: '',
  serviceID: 'airtel-data',
  unique_element: false,
  unique_element_description: false,
  var_count: true,
  variations: {
    countries: [Array],
    foreign_variation: [Array],
    variation_name: 'type',
    variations: [Array],
  },
};
let u = {
  country: 'Cameroon',
  details: {
    id: 'CM',
    flag: 'http://10.0.2.16:8080/resources/images/flags/CM.png',
    text: 'Cameroon',
    currency: 'XAF',
    country_prefix: '237',
  },
};
